# Generated by Django 4.2 on 2025-11-25 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Extra offer', 'Extra offer'), ('Ads', 'Ads'), ('Extra gain', 'Extra gain'), ('Other', 'Other')], default='Product', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
