# Generated by Django 4.2 on 2025-11-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_expense_type_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='myMoney',
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Product', 'Product'), ('Extra offer', 'Extra offer'), ('Ads', 'Ads'), ('Other', 'Other'), ('Extra gain', 'Extra gain')], default='Product', max_length=50),
        ),
    ]
