# Generated by Django 4.2 on 2025-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='in_delivery',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
