# Generated by Django 4.2 on 2025-11-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant_in_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
