# Generated by Django 4.2 on 2025-11-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_comment_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cutomer_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
