# Generated by Django 4.2 on 2025-12-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_cutomer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specialOffer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
